// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.API.Data;

#nullable disable

namespace TechStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Principal #123",
                            Email = "juan@email.com",
                            FechaRegistro = new DateTime(2025, 11, 26, 20, 56, 38, 39, DateTimeKind.Utc).AddTicks(8695),
                            Nombre = "Juan Pérez",
                            Telefono = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Calle Secundaria #456",
                            Email = "maria@email.com",
                            FechaRegistro = new DateTime(2025, 11, 26, 20, 56, 38, 39, DateTimeKind.Utc).AddTicks(9984),
                            Nombre = "María García",
                            Telefono = "555-5678"
                        });
                });

            modelBuilder.Entity("TechStore.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TechStore.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Procesador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TarjetaVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Almacenamiento = "1TB NVMe SSD",
                            Categoria = "Computadora",
                            Descripcion = "Intel i7, 16GB RAM, 1TB SSD, RTX 4060",
                            FechaCreacion = new DateTime(2025, 11, 26, 20, 56, 38, 37, DateTimeKind.Utc).AddTicks(8199),
                            Nombre = "Laptop Gamer Pro",
                            Precio = 1299.99m,
                            Procesador = "Intel Core i7",
                            RAM = "16GB DDR5",
                            Stock = 5,
                            TarjetaVideo = "NVIDIA RTX 4060"
                        },
                        new
                        {
                            Id = 2,
                            Almacenamiento = "512GB SSD",
                            Categoria = "Computadora",
                            Descripcion = "Intel i5, 8GB RAM, 512GB SSD",
                            FechaCreacion = new DateTime(2025, 11, 26, 20, 56, 38, 38, DateTimeKind.Utc).AddTicks(602),
                            Nombre = "Laptop Business",
                            Precio = 899.99m,
                            Procesador = "Intel Core i5",
                            RAM = "8GB DDR4",
                            Stock = 8,
                            TarjetaVideo = "Gráficos Integrados"
                        });
                });

            modelBuilder.Entity("TechStore.API.Models.Pedido", b =>
                {
                    b.HasOne("TechStore.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
